import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/Component/Footer";
import Navbar from "@/Component/Navbar";
import { Toaster } from "react-hot-toast";
import About from "@/Component/About";

const josefin = Josefin_Sans({
  subsets: ["latin"],
});



export const metadata = {
  title: "Tour Booking System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main>
          {children}
          <Toaster position="top-right" />
        </main>
        <Footer />
      </body>
    </html>
  );
}
