import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/Component/Footer";
import Navbar from "@/Component/Navbar";
import { Toaster } from "react-hot-toast";
import About from "@/Component/About";
import { ThemeProvider } from "@/lib/theme-provider";

const josefin = Josefin_Sans({
  subsets: ["latin"],
});



export const metadata = {
  title: "Tour Booking System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main>
            {children}
            <Toaster position="top-right" />
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
